--- 
- name: Install Nginx to Webservers 
  hosts: webservers 
  become: yes 
 
  tasks: 
  - name: Install Nginx 
    apt: 
      name=nginx state=present update_cache=yes 
    when: 
      ansible_os_family == "Debian" 
    notify: 
      - Nginx Systemd 
 
  handlers: 
  - name: Nginx Systemd 
    systemd: 
      name: nginx 
      enabled: yes 
      state: started